version: '3.9'

services:

  prefect-agent:
    build:
      context: ./docker/prefect-agent
      dockerfile: ./Dockerfile
    container_name: agent
    command: "./init.sh"
    volumes:
      - ./.data/prefect/:/home/prefect/.prefect/
      - ./docker/prefect-agent/requirements.txt:/home/prefect/requirements.txt
      - ./docker/prefect-agent/src:/home/prefect/src
    depends_on:
      - redis

  prefect-ui:
    build:
      context: ./docker/prefect-ui
      dockerfile: ./Dockerfile
    container_name: ui
    ports:
      - 4200:4200
    command: "prefect server start --host 0.0.0.0 --port 4200"
    volumes:
      - ./.data/prefect/:/home/prefect/.prefect/
    depends_on:
      - prefect-agent

  redis:
    image: redis:7.0.8-alpine3.17
    container_name: redis
    command: --requirepass secret_redis
    volumes:
        - ./.data/redis:/data
    ports:
      - 6379:6379
    
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:1.18
    container_name: phpredisadmin
    environment:
      - ADMIN_USER=prefect
      - ADMIN_PASS=prefect
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=secret_redis
    ports:
      - 9987:80
    depends_on:
      - redis

  minimal-notebook:
    build:
      context: ./docker/minimal-notebook
      dockerfile: ./Dockerfile
    container_name: notebook
    environment:
      - JUPYTER_TOKEN=secret_token
    volumes:
      - ./docker/minimal-notebook/notebooks:/home/jovyan/work
      - ./.data/prefect/transfers_by_day:/home/jovyan/data/transfers_by_day
    ports:
      - 8888:8888
    depends_on:
      - prefect-agent
