version: '3'

services:

  prefect-agent:
    build:
      context: .
    container_name: agent
    entrypoint: ["./init.sh"]
    volumes:
      - ./flows:/home/prefect/flows
      - ./tasks:/home/prefect/tasks
      - ./utils:/home/prefect/utils
      - ./deployments:/home/prefect/deployments
      - ./.data/prefect:/home/prefect/.prefect

  prefect-ui:
    build:
      context: .
    container_name: ui
    ports:
      - 4200:4200
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0", "--port", "4200"]
    volumes:
      - ./flows:/home/prefect/flows
      - ./tasks:/home/prefect/tasks
      - ./utils:/home/prefect/utils
      - ./deployments:/home/prefect/deployments
      - ./.data/prefect:/home/prefect/.prefect

  redis:
    image: redis:7.0.8-alpine3.17
    container_name: redis
    command: --requirepass secret_redis
    volumes:
        - ./.data/redis:/data
    ports:
      - 6379:6379
    
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:1.18
    container_name: phpredisadmin
    environment:
      - ADMIN_USER=prefect
      - ADMIN_PASS=prefect
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=secret_redis
    ports:
      - 9987:80
    depends_on:
      - redis

