version: '3'

services:

  prefect-agent:
    build:
      context: .
      dockerfile: ./docker/prefect-agent/Dockerfile
    container_name: agent
    command: "./init.sh"
    volumes:
      - ./requirements.txt:/home/prefect/requirements.txt
      - ./flows:/home/prefect/flows
      - ./deployments:/home/prefect/deployments
      - ./src:/home/prefect/src
      - ./.data/prefect/:/home/prefect/.prefect/
    depends_on:
      - redis

  prefect-ui:
    build:
      context: .
      dockerfile: ./docker/prefect-ui/Dockerfile
    container_name: ui
    ports:
      - 4200:4200
    command: "prefect server start --host 0.0.0.0 --port 4200"
    volumes:
      - ./.data/prefect/:/home/prefect/.prefect/
    depends_on:
      - prefect-agent

  redis:
    image: redis:7.0.8-alpine3.17
    container_name: redis
    command: --requirepass secret_redis
    volumes:
        - ./.data/redis:/data
    ports:
      - 6379:6379
    
  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:1.18
    container_name: phpredisadmin
    environment:
      - ADMIN_USER=prefect
      - ADMIN_PASS=prefect
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - REDIS_1_AUTH=secret_redis
    ports:
      - 9987:80
    depends_on:
      - redis

  notebook:
    build:
      context: .
      dockerfile: ./docker/minimal-notebook/Dockerfile
    container_name: notebook
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./.data/prefect/transfers_by_day:/home/jovyan/data/transfers_by_day
    ports:
      - 8888:8888
    depends_on:
      - prefect-agent
