version: '3'

services:

  prefect-agent:
    build:
      context: .
    container_name: agent
    entrypoint: ["prefect", "agent", "start", "-q", "default"]
    volumes:
      - ./flows:/home/prefect/flows

  prefect-ui:
    build:
      context: .
    container_name: ui
    ports:
      - 4200:4200
    entrypoint: ["prefect", "server", "start", "--host", "0.0.0.0", "--port", "4200"]
    volumes:
      - ./flows:/home/prefect/flows
